In [3]:
import torch
import pypose as pp


# 1. Initialize the tensor

In [4]:
i = [[0, 0, 1, 2], [0, 2, 1, 2]]
v = torch.arange(16).view((-1, 2, 2)).to(dtype=torch.float32)
x = pp.sbktensor(i, v, size=(3, 3), dtype=torch.float32)
print(x.to_sparse_coo().to_dense())


tensor([[ 0.,  1.,  0.,  0.,  4.,  5.],
        [ 2.,  3.,  0.,  0.,  6.,  7.],
        [ 0.,  0.,  8.,  9.,  0.,  0.],
        [ 0.,  0., 10., 11.,  0.,  0.],
        [ 0.,  0.,  0.,  0., 12., 13.],
        [ 0.,  0.,  0.,  0., 14., 15.]])


# 2. Example operations

In [7]:
# operation between two SbkTensor
x = x + x
print(type(x))
print(x.to_sparse_coo().to_dense())

x = x @ x
print(type(x))
print(x.to_sparse_coo().to_dense())

# operation between SbkTensor and a scalar
x = x * 2
print(type(x))
print(x.to_sparse_coo().to_dense())


<class 'pypose.sparse.sbktensor.SbkTensor'>
tensor([[2.2528e+04, 3.9936e+04, 0.0000e+00, 0.0000e+00, 9.4118e+07, 1.0135e+08],
        [7.9872e+04, 1.4234e+05, 0.0000e+00, 0.0000e+00, 1.5123e+08, 1.6287e+08],
        [0.0000e+00, 0.0000e+00, 5.7555e+07, 6.3913e+07, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.1014e+07, 7.8859e+07, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.4469e+08, 2.6346e+08],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.8372e+08, 3.0549e+08]])
<class 'pypose.sparse.sbktensor.SbkTensor'>
tensor([[3.6973e+09, 6.5840e+09, 0.0000e+00, 0.0000e+00, 5.1792e+16, 5.5765e+16],
        [1.3168e+10, 2.3449e+10, 0.0000e+00, 0.0000e+00, 8.3244e+16, 8.9629e+16],
        [0.0000e+00, 0.0000e+00, 7.8513e+15, 8.7186e+15, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 9.6874e+15, 1.0758e+16, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.3462e+17, 1.4495e+17],
        [