In [1]:
import torch
import pypose as pp


# 1. Initialize the tensor

In [2]:
i = [[0, 0, 1, 2], [0, 2, 1, 2]]
v = torch.arange(16).view((-1, 2, 2)).to(dtype=torch.float32)
x = pp.sbktensor(i, v, size=(3, 3), dtype=torch.float32)
print(x.to_sparse_coo().to_dense())


tensor([[ 0.,  1.,  0.,  0.,  4.,  5.],
        [ 2.,  3.,  0.,  0.,  6.,  7.],
        [ 0.,  0.,  8.,  9.,  0.,  0.],
        [ 0.,  0., 10., 11.,  0.,  0.],
        [ 0.,  0.,  0.,  0., 12., 13.],
        [ 0.,  0.,  0.,  0., 14., 15.]])


# 2. Example operations

In [4]:
x = x + x
print(type(x))
print(x.to_sparse_coo().to_dense())

x = x @ x
print(type(x))
print(x.to_sparse_coo().to_dense())


<class 'pypose.sparse.sbktensor.SbkTensor'>
tensor([[  16.,   24.,    0.,    0.,  992., 1072.],
        [  48.,   88.,    0.,    0., 1568., 1712.],
        [   0.,    0., 1232., 1368.,    0.,    0.],
        [   0.,    0., 1520., 1688.,    0.,    0.],
        [   0.,    0.,    0.,    0., 2608., 2808.],
        [   0.,    0.,    0.,    0., 3024., 3256.]])
<class 'pypose.sparse.sbktensor.SbkTensor'>
tensor([[1.4080e+03, 2.4960e+03, 0.0000e+00, 0.0000e+00, 5.8824e+06, 6.3342e+06],
        [4.9920e+03, 8.8960e+03, 0.0000e+00, 0.0000e+00, 9.4520e+06, 1.0179e+07],
        [0.0000e+00, 0.0000e+00, 3.5972e+06, 3.9946e+06, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.4384e+06, 4.9287e+06, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.5293e+07, 1.6466e+07],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.7733e+07, 1.9093e+07]])
